- .github/workflows/doc-build.yml
should fix https://github.com/eclipse-openbsw/openbsw/actions/runs/11705910588
> Fix doc-build workflow permissions

- .github/workflows/release.yml
Signed-off-by: Thomas Frank <thomas.frank@esrlabs.com>
> Add 'contents-write' permission to release workflow

- doc/github_pages/index.html
Add Correct path to doxygen html in index.html
> Add Correct path to doxygen html in index.html

- libs/bsw/estd/src/estd/assert.cpp
> Make estd_assert compile-flags independent

- .github/workflows/code-coverage.yml
- Changes made in code-coverage.yml
> Fix code coverage action

- doc/github_pages/index.html
- Changes made in doc/github_pages/index.html
Output for reference:
> Style documentation root page

- libs/bsw/uds/doc/application_config_example.rst
- libs/bsw/uds/doc/index.rst
- libs/bsw/uds/doc/user/connection.rst
- libs/bsw/uds/doc/user/dispatcher.rst
- libs/bsw/uds/doc/user/index.rst
- libs/bsw/uds/doc/user/runtime_diag_tree.puml
- libs/bsw/uds/doc/user/sessions.rst
> Documentation for UDS' dispatcher and connection parts

- executables/referenceApp/platforms/s32k148evb/main/src/bsp/startUp.S
> Fix hard fault due to uninitialized MPU BSS section

- libs/bsw/estd/include/estd/slice.h
> Remove internal link

- platforms/s32k1xx/bsp/bspInterruptsImpl/include/interrupts/suspendResumeAllInterrupts.h
> Add compiler barriers to S32K1 interrupts

- .github/workflows/build.yml
The test for C++23 support can be added trivially.
> Support C++23

- executables/referenceApp/platforms/s32k148evb/bspConfiguration/include/bsp/adc/AnalogInput.h
- libs/bsp/bspInputManager/include/inputManager/DigitalInput.h
- libs/bsp/bspInputManager/src/inputManager/DigitalInput.cpp
- platforms/s32k1xx/bsp/bspAdc/include/adc/Adc.h
> Use bitmasks for ADC configuration

- libs/safety/safeMemory/src/safeMemory/MemoryProtection.cpp
> Fix compilation error caused by -Werror=array-bounds= in MemoryProtection.cpp

- .ci/build.py
- .ci/build_matrix.py
- .ci/code_coverage.py
- .ci/doxygen-docs.py
- .ci/format.py
- .ci/pytest.py
- .ci/sphinx-docs.py
- .github/workflows/build.yml
- .github/workflows/code-coverage.yml
- .github/workflows/doxygen-build.yml
- .github/workflows/format.yml
- .github/workflows/run-pytest-on-posix.yml
- .github/workflows/sphinx-doc-build.yml
- .gitignore
- docker/Dockerfile.dev
- docker/Dockerfile.docs
- docker/README.md
- docker/docker-compose.yaml
> Python scripts for executable logic

- .ci/build.py
> Set CXX to g++ instead of gcc

- doc/learning/setup/index.rst
- doc/learning/setup/setup_s32k148_gdbserver.rst
- executables/referenceApp/platforms/s32k148evb/main/CMakeLists.txt
> Add dependency on the linker script in cmake

- .ci/code_coverage.py
> Show output if a unit test fails on the CI

- executables/referenceApp/application/src/app/app.cpp
- libs/bsw/asyncFreeRtos/doc/user/startup_sequence.rst
- libs/bsw/asyncFreeRtos/include/async/FreeRtosAdapter.h
- libs/bsw/asyncFreeRtos/include/async/TaskContext.h
- libs/bsw/asyncFreeRtos/include/async/TaskInitializer.h
- libs/bsw/asyncFreeRtos/test/gtest/src/async/AsyncTest.cpp
- libs/bsw/asyncFreeRtos/test/gtest/src/async/FreeRtosAdapterTest.cpp
- libs/bsw/asyncFreeRtos/test/gtest/src/async/TaskInitializerTest.cpp
> asyncFreeRtos: make idle task handling a more usual case

- executables/referenceApp/application/src/systems/DemoSystem.cpp
- executables/referenceApp/application/src/systems/EthernetSystem.cpp
- executables/referenceApp/configuration/include/systems/IEthernetDriverSystem.h
- executables/referenceApp/platforms/posix/main/include/systems/TapEthernetSystem.h
- executables/referenceApp/platforms/s32k148evb/main/include/systems/S32K148EvbEthernetSystem.h
- libs/bsw/cpp2ethernet/include/udp/util/UdpEchoTestServer.h
- libs/bsw/cpp2ethernet/src/udp/util/UdpEchoTestServer.cpp
- platforms/posix/bsp/tapEthernetDriver/include/TapEthernetDriver.h
- platforms/posix/bsp/tapEthernetDriver/src/TapEthernetDriver.cpp
- platforms/s32k1xx/bsp/bspEthernet/include/ethernet/EnetDriver.h
- platforms/s32k1xx/bsp/bspEthernet/src/ethernet/EnetDriver.cpp
Adds missing CRC based filter bit calculation to ENET driver and multicast join to DemoSystem.
> Add UDP multicast support

- tools/elf/elf-analyzer-config.json
> Add elf-analyzer-config.json to main

- doc/github_pages/index.html
> Add MUC++ talk to publications

- .ci/build.py
- .github/workflows/build.yml
> Update build.yml to upload s32k148 artifacts
