eclipse-openbsw/openbsw

- .github/workflows/docs.yml
Without this each doc page is marked as UNOFFICIAL BUILD in the footer.
Signed-off-by: Thomas Frank <thomas@franks-im-web.de>
> Mark documentation as official when built on gh

- .github/workflows/doc-build.yml
- .github/workflows/doc-publish.yml
- .github/workflows/release.yml
Adds a release workflow which is triggered every time a tag matching `v*.*` is pushed.
Documentation matching the commit is built and attached.
Release Notes are empty for now. We need to think about how we want to handle them in the future.
It is always possible to add them manually after the action ran.
> Add release workflow

- .github/workflows/doc-publish.yml
Here it says the permissions can't be upgraded in a called workflow:
https://docs.github.com/en/actions/sharing-automations/reusing-workflows#supported-keywords-for-jobs-that-call-a-reusable-workflow
> Call doc build with the required permissions

- .github/workflows/doc-publish.yml
actions-gh-pages requires 'contents: write' as well
> Add required permissions to all steps in doc-publish

- README.md
- doc/github_pages/index.html
Adds links to openbsw related publications
> Add links to talk & article

- CONTRIBUTING.md
- NOTICE.md
fixes #22 ``The links to set up a working environment, Coding Guidelines and issues in CONTRIBUTING.md are not available``
> Fix links in CONTRIBUTING.md

- .github/workflows/build.yml
This pull request introduces a common build action for both POSIX and S32K platforms. The following changes have been made:
**build.yml**: Created a unified build action that supports both POSIX and S32K platforms.
> Add GitHub Actions for POSIX and S32K148 platform build

- Filelists.cmake
This commit fixes unit-tests AND _code coverage_ info as it re-adds debug symbols to debug build (for _code coverage_) and causes _googletest's_ `EXPECT_DEATH` to fail as expected while running `CrcTests.CalculateCRCWithInvalidData`. Further changes in a separate PR might be required for `estd_assert` macro for unit test builds.
> Fix debug symbols on debug build

- .github/workflows/build.yml
**Used hash key concept:** The cache key is based on the source files and toolchain. If there are changes in these, a new build is triggered; otherwise, the cache is used.
> Add cache for build artifacts

- .github/workflows/code-coverage.yml
- .github/workflows/publish.yml
- doc/github_pages/index.html
This GitHub Action automates the generation and publishing of code coverage reports of the modules. It captures code coverage data using lcov, filters out third-party, mock files, gtest folders and system libraries.
Then it generates an HTML report that is deployed to GitHub Pages. 
Changes made:
Added code-coverage.yml
Added CodeCoverage.cmake
Made changes in CMakeLists.txt
> GitHub action for code coverage 

- executables/referenceApp/platforms/posix/main/src/main.cpp
- platforms/posix/bsp/bspMcu/src/reset/softwareSystemReset.cpp
- platforms/posix/bsp/bspStdio/src/bsp/stdIo/stdIo.cpp
Fix posix console missing chars, restore terminal attributes on exit
Change-Id: Ie2a581ddadba0e76b1a9d2dc7ab4c8cd3de63785
> Fix posix console missing chars, restore terminal attributes on exit

- libs/3rdparty/freeRtos/mock/include/os/FreeRtosMock.h
- libs/3rdparty/freeRtos/mock/include/task.h
- libs/3rdparty/freeRtos/mock/src/os/FreeRtosMock.cpp
- libs/bsw/asyncFreeRtos/include/async/FreeRtosAdapter.h
- libs/bsw/asyncFreeRtos/include/async/TaskContext.h
- libs/bsw/asyncFreeRtos/include/async/TaskInitializer.h
- libs/bsw/asyncFreeRtos/test/gtest/src/async/AsyncTest.cpp
- libs/bsw/asyncFreeRtos/test/gtest/src/async/FreeRtosAdapterTest.cpp
- libs/bsw/asyncFreeRtos/test/gtest/src/async/TaskContextTest.cpp
- libs/bsw/asyncFreeRtos/test/gtest/src/async/TaskInitializerTest.cpp
- libs/bsw/asyncImpl/include/async/EventPolicy.h
> Remove usage of FreeRTOS timers from asyncFreeRtos

- .github/workflows/code-coverage.yml
- .github/workflows/publish.yml
- README.md
- Removed coverage.js that was previously written for converting` coverage.info` to `Json` 
- Updated README.md with links to workflow badges
Output of badges for reference:
> Add workflow badges to README.md

- docker/Dockerfile.dev
- docker/Dockerfile.docs
- docker/README.md
- docker/docker-compose.yaml
Add Dockerfiles for development and documentation, Docker Compose file, and README with usage instructions
**Development Dockerfile:**
This Dockerfile is designed for development purposes and includes:
- POSIX and S32K builds
- Unit test builds
- Clang format and CMake format
- Clang tidy
- Code coverage tools
**Documentation Dockerfile:**
This Dockerfile is dedicated to documentation-related tasks and includes:
- Sphinx documentation
- Doxygen documentation
- Documentation coverage
> CI: Add Dockerfiles for dev and docs

- .github/workflows/build.yml
- .github/workflows/run-pytest-on-posix.yml
This adds a github action to run integration tests on the posix build.
The `ubuntu-latest` runner was built with SocketCAN support but is missing the kernel module file for `vcan`.
Running `sudo apt install linux-modules-extra-$(uname -r)` adds this kernel module file, then `vcan0` can be set up and the tests work.
> Add github action to run pytest on posix build

- libs/bsw/cpp2can/test/gtest/src/can/transceiver/AbstractCANTransceiverTest.cpp
build setup:
export CFLAGS=-fsanitize=address
export CXXFLAGS=-fsanitize=address
export LDFLAGS=-fsanitize=address
export CC=clang
export CXX=clang++
-DCMAKE_BUILD_TYPE=Debug
-DBUILD_TARGET_PLATFORM=POSIX
-DPLATFORM_SUPPORT_CAN=ON
-DPLATFORM_SUPPORT_IO=ON
-DPLATFORM_SUPPORT_UDS=ON
The error is reproduced on a posix build by:
export ASAN_OPTIONS=detect_leaks=0
./openbsw/libs/bsw/uds/test/gtest/udsTest --gtest_filter=UdsIntegration.positive_response
> Fix clang asan error in AbstractCANTransceiverTest.testNotifySentListeners

- libs/bsw/estd/examples/deque.cpp
- libs/bsw/estd/examples/uncopyable.cpp
Fix build failures for target estdExamples due to '#pragma clang' with gcc compiler
Only seen when building executables/unitTest
> Fix build failures for target estdExamples

- .github/workflows/build.yml
- .github/workflows/run-pytest-on-posix.yml
- Updated actions/cache and actions/cache/restore to version 4 in run-pytest-on-posix.yml and build.yml which ensures that the fail-on-cache-miss: true flag works as expected.
- Updated key value for actions/cache/restore to make pytest work.
> Fix: cache miss issue and key value error

- .github/workflows/format.yml
- .treefmt.toml
> WARN no formatter for path: docker/Dockerfile.dev
> WARN no formatter for path: docker/Dockerfile.docs
> WARN no formatter for path: libs/bsw/uds/doc/user/runtime_diag_tree.puml
- Added files with warnings to excludes list in .treefmt.toml
- Updated format.yml to trigger on push events
> Fix: Warnings in GitHub Action of format.yml

- .github/workflows/code-coverage.yml
The code-coverage.yml workflow creates the directories:
cmake-build-unit-tests, code_coverage, and coverage_badges with root permissions. This happens because the command for running unit tests is executed inside a Docker image in code-coverage.yml, which generates the directories with root permissions. Therefore, this PR changes the ownership of these directories and assigns them to the Jenkins user and group.
Jira : [https://esrlabs.atlassian.net/browse/BS-2744](url)
> Fix directories permissions in code-coverage.yml

- .github/workflows/code-coverage.yml
- Utilize sscache to speed up the compilation process for unit builds.
- Eliminate the need for Docker containers in the CI workflow to simplify the setup.
- Implement actions/cache to store cmake-build-unit-tests artifacts to ensure these cached artifacts can be reused across different workflows to improve efficiency.
> Integrate sscache for faster unit build compilation

- .github/workflows/code-coverage.yml
- Removed restore keys option from actions/cache@v3 to prevent restoring caches that are close but not an exact match.
- Deleted cmake-build-unit-tests directory before running unit test build to ensure a clean build environment.
- Added --ignore-errors source to genhtml command to prevent HTML generation failures if files are not found.
This commit addresses the "cannot read" error caused by old cache contents.
> Fix: CI breaks build on removed files

- Filelists.cmake
- doc/learning/overview.rst
- doc/learning/tracing/index.rst
- executables/referenceApp/application/src/app/app.cpp
- executables/referenceApp/application/src/systems/DemoSystem.cpp
- executables/referenceApp/platforms/s32k148evb/bspConfiguration/src/bsp/SystemTimer/SystemTimer.cpp
- libs/bsw/bsp/include/bsp/timer/SystemTimer.h
- libs/bsw/runtime/CMakeLists.txt
- libs/bsw/runtime/include/runtime/RuntimeMonitor.h
- libs/bsw/runtime/include/runtime/Tracer.h
- libs/bsw/runtime/src/runtime/Tracer.cpp
- platforms/posix/bsp/bspSystemTime/src/bsp/time/systemTimer.cpp
- tools/tracing/bt_plugin_openbsw.py
- tools/tracing/trace_convert.py
> Add tracing feature

- .github/workflows/puncover_tool.yml
- .gitignore
- .treefmt.toml
- admin/cmake/ArmNoneEabi.cmake
- For viewing the Stack Usage on puncover
- .su files will be generated under cmake-build-s32k148
- View Stack Worst-Case Scenarios and Stack Usage on puncover tools/puncover_tool/output/index.html
- Add generated tools/puncover_tool/output to .gitignore
> Add stack usage in ArmNoneEabi.cmake for Puncover

- README.md
-  This badge displays the build status of the latest push event on the main branch, including merges from pull requests.
Clicking on the badge redirects to the corresponding GitHub Actions workflow run:
Output can be viewed from here: [link](https://github.com/esrlabs/openbsw/tree/StatusBadge?tab=readme-ov-file#build-status-)
> Show build status of Posix, S32k148

- executables/referenceApp/platforms/s32k148evb/main/src/bsp/startUp.S
Fixe comments in `startup.S` to not emit warnings due to nested `/*`
> Fix Warnings for Comments in Clang

- libs/bsp/bspCharInputOutput/src/charInputOutput/bspIo.cpp
- libs/bsw/cpp2can/src/can/filter/IntervalFilter.cpp
- libs/bsw/transport/src/LogicalAddress.cpp
- libs/bsw/uds/src/uds/services/routinecontrol/RequestRoutineResults.cpp
- libs/bsw/uds/src/uds/services/routinecontrol/StartRoutine.cpp
- libs/bsw/uds/src/uds/services/routinecontrol/StopRoutine.cpp
By replacing std usage with etl counterparts, code will compile in more cases in ETL_NO_STL mode.
This is preparational work for the upcoming ETL release from which we want to include etl::closure and in turn etl::tuple. This requires decoupling etl from std if we want to keep ETL_NO_STL mode.
> Remove dependencies on std

- libs/bsw/lifecycle/include/lifecycle/AsyncLifecycleComponent.h
- libs/bsw/lifecycle/include/lifecycle/ILifecycleComponent.h
- libs/bsw/lifecycle/include/lifecycle/LifecycleComponent.h
- libs/bsw/lifecycle/include/lifecycle/SimpleLifecycleComponent.h
- libs/bsw/lifecycle/include/lifecycle/SingleContextLifecycleComponent.h
This should allow compiler to ommit the generation of dtr for lifecycle components wrapped in typed_mem.
> Make ILifecycleComponent's dtr protected non-virtual

- platforms/posix/bsp/socketCanTransceiver/test/gtest/CMakeLists.txt
Fix build error, when build directory has whitespaces in it.
Fixes #140
> Fix error when built for directory with whitespaces

- .github/workflows/build.yml
Reduce the amount of checks by deleting checks for C++17 and C++23 compilation. Also remove check for compilation with unspecified config.
> Reduce the amount of CI checks

- executables/referenceApp/platforms/s32k148evb/main/linkerscript/application.dld
- executables/referenceApp/platforms/s32k148evb/main/src/systems/S32K148EvbEthernetSystem.cpp
EthernetDescriptors were not mapped, it could happen, that romp and data sections overlap, which leads to linker errors.
The CRC section at the end of the flash also overlapped with data_rom section, but this problem would only occur if flash is almost full.
Additionally, unused sections were removed to cleanup the linker script a bit.
Thanks to Martin Mössmer and Roland Reichwein for support.
> Fix linkerscript errors

- cmake/toolchains/ArmNoneEabi-clang.cmake
- platforms/s32k1xx/bsp/bspAdc/include/adc/Adc.h
-lc causes newlib to be linked and causing duplicate symbols, since we also define snprintf().
Fixing an unused argument also.
> Fix build with s32k148-clang

- doc/learning/SysTest/HW_Testing_Guide.rst
- doc/learning/console/pwmConsole.rst
- doc/learning/hwio/index.rst
- executables/referenceApp/platforms/s32k148evb/bspConfiguration/doc/user/bspIo_outputPwm.rst
- executables/referenceApp/platforms/s32k148evb/bspConfiguration/include/bsp/io/outputPwm/PwmSupport.h
- executables/referenceApp/platforms/s32k148evb/bspConfiguration/include/bsp/io/outputPwm/PwmSupportConfiguration.hpp
- executables/referenceApp/platforms/s32k148evb/bspConfiguration/include/bsp/io/outputPwm/outputPwmConfiguration.h
- executables/referenceApp/platforms/s32k148evb/bspConfiguration/include/bsp/io/outputPwm/outputPwmConfigurationStrings.h
- executables/referenceApp/platforms/s32k148evb/bspConfiguration/src/bsp/io/outputPwm/PwmSupport.cpp
- executables/unitTest/bsp/bspConfiguration/include/bsp/io/outputPwm/outputPwmConfiguration.h
- executables/unitTest/bsp/bspConfiguration/include/bsp/io/outputPwm/outputPwmConfigurationStrings.h
The red LED is already controlled via GPIO in combination with button 3 on the eval board.
> Remove red LED from PwmSupport in ReferenceApp
